language: scala

scala:
   - 2.9.3

jdk:
  - oraclejdk7
  - openjdk7

cache:
  directories:
  - $HOME/.m2

after_success:
  - mvn cobertura:cobertura coveralls:cobertura

notifications:
  email:
    - connolly.st@gmail.com